version: 2
jobs:
  test-ruby:
    docker:
      - image: circleci/ruby:2.4.4-jessie
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: cd ./ruby && bundle install
      - run:
          name: Run tests
          command: cd ./ruby && bundle exec rspec run.rb

  test-javascript:
    docker:
      - image: circleci/node:10.8-browsers
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: cd ./javascript && npm install
      - run:
          name: Run tests
          command: cd ./javascript && npm test

  test-python:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd ./python && pip install -r requirements.txt --user
      - run:
          name: Run tests
          command: cd ./python && pytest safe_spaces_test.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - test-ruby
      - test-javascript
      - test-python

