version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.4.4-jessie
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: cd ./ruby && bundle install
      - run:
          name: Run tests
          command: cd ./ruby && bundle exec rspec run.rb

workflows:
  version: 2
  build_and_test:
    jobs:
      - test