version: 2
jobs:
  test:
    working_directory: ~/ruby
    docker:
      - image: circleci/ruby:2.4.4-jessie
    steps:
      - checkout
      - run: bundle exec rspec run.rb

workflows:
  version: 2
  build_and_test:
    jobs:
      - test